version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/lib/tempehlab/mosquitto/passwd:/mosquitto/config/passwd
      - /var/lib/tempehlab/mosquitto/acl:/mosquitto/config/acl
      - /var/lib/tempehlab/mosquitto/data:/mosquitto/data
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    environment: ["TZ=Europe/Prague"]
    ports: ["1880:1880"]
    volumes:
      - /var/lib/tempehlab/nodered:/data
      - /var/lib/tempehlab/sqlite:/data/sqlite
    depends_on: [mosquitto]
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports: ["80:80"]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/lib/tempehlab/ota:/srv/ota
    depends_on: [nodered]
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    ports: ["9999:8080"]
    environment:
      - TZ=Europe/Prague
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    environment:
      - TZ=Europe/Prague
      - GF_SECURITY_ADMIN_USER=patrik
      - GF_SECURITY_ADMIN_PASSWORD=heslojesilne
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
#      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      # perzistentní data grafany
      - /var/lib/tempehlab/grafana:/var/lib/grafana
      # provisioning (datasources/dashboards)
      #- ./grafana/provisioning:/etc/grafana/provisioning:ro
      # přimountujeme DB i do grafany (pro datasource plugin)
      - /var/lib/tempehlab/sqlite:/var/lib/sqlite:ro
    restart: unless-stopped
