version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883"]
    volumes:
      # config z repozitáře jen na čtení
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      # runtime soubory z hosta (mimo repo)
      - /var/lib/tempehlab/mosquitto/passwd:/mosquitto/config/passwd
      - /var/lib/tempehlab/mosquitto/acl:/mosquitto/config/acl
      # perzistentní data
      - /var/lib/tempehlab/mosquitto/data:/mosquitto/data
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    environment: ["TZ=Europe/Prague"]
    ports: ["1880:1880"]
    volumes:
      - /var/lib/tempehlab/nodered:/data
      - /var/lib/tempehlab/sqlite:/data/sqlite
    depends_on: [mosquitto]
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports: ["80:80"]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/lib/tempehlab/ota:/srv/ota
    depends_on: [nodered]
    restart: unless-stopped
