version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/acl:/mosquitto/config/acl
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fermenter
      POSTGRES_USER: app
      POSTGRES_PASSWORD: change-me
    volumes:
      - ./postgres/data:/var/lib/postgresql/data      # (ideálně na SSD)
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports: ["5432:5432"]
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    environment: ["TZ=Europe/Prague"]
    ports: ["1880:1880"]
    volumes:
      - ./nodered:/data
    depends_on: [mosquitto, postgres]
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports: ["80:80"]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/ota:/srv/ota
    depends_on: [nodered]
    restart: unless-stopped
