name: Deploy on RPi (self-hosted)

on:
  push:
    branches: ["**"]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare secrets & files
        env:
          DEV_PW: ${{ secrets.MQTT_DEV001_PW }}
          NR_PW:  ${{ secrets.MQTT_DEV001_PW }}
        run: |
          set -e
          sudo install -d -m 700 -o root -g root /var/lib/tempehlab/mosquitto
          sudo install -d -m 700 -o root -g root /var/lib/tempehlab/mosquitto/data
          sudo touch /var/lib/tempehlab/mosquitto/passwd /var/lib/tempehlab/mosquitto/acl
          sudo chown root:root /var/lib/tempehlab/mosquitto/passwd /var/lib/tempehlab/mosquitto/acl
          sudo chmod 600 /var/lib/tempehlab/mosquitto/passwd /var/lib/tempehlab/mosquitto/acl

          docker run --rm -v "/var/lib/tempehlab/mosquitto:/mosquitto" eclipse-mosquitto:2 \
            sh -c "mosquitto_passwd -b /mosquitto/passwd dev-001 \"$DEV_PW\" && \
                   mosquitto_passwd -b /mosquitto/passwd nodered \"$NR_PW\""

      - name: Pull images (optional)
        working-directory: tempehlab
        run: docker compose pull || true

      - name: Deploy (compose up)
        working-directory: tempehlab
        run: |
          docker compose down
          docker compose up -d --remove-orphans

      - name: Show status
        run: docker ps
